# Generated by Django 6.0.5 on 2026-05-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('calificacion', models.IntegerField()),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_estreno', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
