# Generated by Django 6.0.5 on 2026-05-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='generos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='total_capitulos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
