# Generated by Django 6.0.5 on 2026-05-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_serie_generos_serie_total_capitulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='calificacion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
