# Generated by Django 6.0.5 on 2026-06-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
