# Generated by Django 6.0.5 on 2026-06-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_serie_backdrop_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='id_tmdb',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
