# Generated by Django 6.0.5 on 2026-06-11 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_serie_id_tmdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEpisodeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_episode_lists', to='series.perfil')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('perfil', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CustomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_lists', to='series.perfil')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('perfil', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField()),
                ('total_episodes', models.IntegerField(default=0)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='series.serie')),
            ],
            options={
                'ordering': ['season_number'],
                'unique_together': {('serie', 'season_number')},
            },
        ),
        migrations.CreateModel(
            name='CustomEpisodeListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('episode_title', models.CharField(blank=True, max_length=300, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('custom_episode_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='series.customepisodelist')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_episode_list_entries', to='series.serie')),
            ],
            options={
                'verbose_name_plural': 'Custom episode list entries',
                'ordering': ['order', 'added_at'],
                'unique_together': {('custom_episode_list', 'serie', 'season_number', 'episode_number')},
            },
        ),
        migrations.CreateModel(
            name='CustomListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('custom_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='series.customlist')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_list_entries', to='series.serie')),
            ],
            options={
                'verbose_name_plural': 'Custom list entries',
                'ordering': ['order', 'added_at'],
                'unique_together': {('custom_list', 'serie')},
            },
        ),
        migrations.CreateModel(
            name='UserSeasonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodes_watched', models.IntegerField(default=0)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons_progress', to='series.perfil')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='series.season')),
            ],
            options={
                'verbose_name_plural': 'User season progress',
                'unique_together': {('perfil', 'season')},
            },
        ),
        migrations.CreateModel(
            name='UserSeriesProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watching', 'Viendo'), ('completed', 'Completada'), ('paused', 'Pausada'), ('dropped', 'Abandonada')], default='watching', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('current_season', models.IntegerField(default=1)),
                ('current_episode', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_progress', to='series.perfil')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='series.serie')),
            ],
            options={
                'verbose_name_plural': 'User series progress',
                'unique_together': {('perfil', 'serie')},
            },
        ),
    ]
