# Generated by Django 6.0.5 on 2026-06-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0007_customepisodelist_customlist_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='total_temporadas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
