# Generated by Django 6.0.5 on 2026-06-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0008_serie_total_temporadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userseriesprogress',
            name='status',
            field=models.CharField(choices=[('plan_to_watch', 'Por Ver'), ('watching', 'Viendo'), ('completed', 'Completada'), ('paused', 'Pausada'), ('dropped', 'Abandonada')], default='plan_to_watch', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserSeasonProgress',
        ),
    ]
