# Generated by Django 6.0.5 on 2026-06-20 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0009_alter_userseriesprogress_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('plan_to_watch', 'Por Ver'), ('watching', 'Viendo'), ('completed', 'Completada'), ('paused', 'Pausada'), ('dropped', 'Abandonada')], max_length=20)),
                ('score_momento', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('comment_momento', models.TextField(blank=True, max_length=1000, null=True)),
                ('captura_favorita', models.ImageField(blank=True, null=True, upload_to='capturas_actividad/')),
                ('es_silencioso', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_actividades', to='series.perfil')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_eventos', to='series.serie')),
            ],
            options={
                'verbose_name_plural': 'Historial de actividades',
                'ordering': ['-created_at'],
            },
        ),
    ]
