# Generated by Django 6.0.5 on 2026-06-21 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0010_historialactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('like', 'Me gusta'), ('dislike', 'Discrepo')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='series.historialactividad')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_votos', to='series.perfil')),
            ],
            options={
                'unique_together': {('perfil', 'actividad')},
            },
        ),
    ]
