# Generated by Django 6.0.5 on 2026-06-22 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0011_votoactividad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='series.userseriesprogress')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_actividad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de actividad',
                'verbose_name_plural': 'Comentarios de actividad',
                'ordering': ['created_at'],
            },
        ),
    ]
