# Generated by Django 6.0.5 on 2026-06-22 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0012_comentarioactividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='series.historialactividad'),
        ),
    ]
