# Generated by Django 6.0.5 on 2026-06-25 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0013_alter_comentarioactividad_actividad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField()),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='series.season')),
            ],
            options={
                'ordering': ['episode_number'],
                'unique_together': {('season', 'episode_number')},
            },
        ),
        migrations.CreateModel(
            name='ComunidadPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('natural', 'Publicación Libre'), ('foro', 'Foro de Debate'), ('encuesta', 'Encuesta')], default='natural', max_length=15)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('texto', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='comunidad/imagenes/')),
                ('video', models.FileField(blank=True, null=True, upload_to='comunidad/videos/')),
                ('gif_url', models.URLField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('teorias', 'Teorías'), ('criticas', 'Críticas'), ('debates', 'Debates'), ('noticias', 'Noticias'), ('ninguna', 'Ninguna')], default='ninguna', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capitulo_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_mencionados', to='series.capitulo')),
                ('serie_vinculada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_mencionados', to='series.serie')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_comunidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post de Comunidad',
                'verbose_name_plural': 'Posts de Comunidad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EncuestaOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_encuesta', to='series.comunidadpost')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='series.comunidadpost')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_comunidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta de comunidad',
                'verbose_name_plural': 'Respuestas de comunidad',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EncuestaVoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='series.encuestaopcion')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_encuestas', to='series.perfil')),
            ],
            options={
                'unique_together': {('perfil', 'opcion')},
            },
        ),
        migrations.CreateModel(
            name='VotoComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('like', 'Me gusta'), ('dislike', 'Discrepo')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_votos_comunidad', to='series.perfil')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='series.comunidadpost')),
            ],
            options={
                'unique_together': {('perfil', 'post')},
            },
        ),
    ]
