# Generated by Django 6.0.5 on 2026-07-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0014_capitulo_comunidadpost_encuestaopcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidadpost',
            name='track_artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comunidadpost',
            name='track_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comunidadpost',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
