# Generated by Django 6.0.5 on 2026-07-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0015_comunidadpost_track_artist_comunidadpost_track_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidadpost',
            name='track_artist',
        ),
        migrations.RemoveField(
            model_name='comunidadpost',
            name='track_title',
        ),
        migrations.RemoveField(
            model_name='comunidadpost',
            name='youtube_video_id',
        ),
    ]
