# Generated by Django 6.0.5 on 2026-07-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0016_remove_comunidadpost_track_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidadpost',
            name='track_artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comunidadpost',
            name='track_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comunidadpost',
            name='track_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
