# Generated by Django 6.0.5 on 2026-07-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0017_comunidadpost_track_artist_comunidadpost_track_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidadpost',
            name='track_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
