# Generated by Django 6.0.5 on 2026-07-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0018_comunidadpost_track_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidadpost',
            name='jamendo_track_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
