# Generated by Django 6.0.5 on 2026-07-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0019_comunidadpost_jamendo_track_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidadpost',
            name='jamendo_track_id',
        ),
        migrations.RemoveField(
            model_name='comunidadpost',
            name='track_artist',
        ),
        migrations.RemoveField(
            model_name='comunidadpost',
            name='track_id',
        ),
        migrations.RemoveField(
            model_name='comunidadpost',
            name='track_image',
        ),
        migrations.RemoveField(
            model_name='comunidadpost',
            name='track_title',
        ),
        migrations.AddField(
            model_name='comunidadpost',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='comunidad/audios/'),
        ),
        migrations.AddField(
            model_name='comunidadpost',
            name='audio_artista',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comunidadpost',
            name='audio_titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
