# Generated by Django 6.0.5 on 2026-07-05 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0020_remove_comunidadpost_jamendo_track_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancionBiblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('artista', models.CharField(default='Desconocido', max_length=255)),
                ('archivo_completo', models.FileField(upload_to='biblioteca_audios/')),
                ('es_oficial', models.BooleanField(default=False)),
                ('hash_md5', models.CharField(help_text='Para evitar archivos duplicados', max_length=32, unique=True)),
                ('fecha_adicion', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('archivo_fragmento', models.FileField(blank=True, null=True, upload_to='publicaciones_audios/')),
                ('segundo_inicio', models.FloatField(blank=True, null=True)),
                ('segundo_fin', models.FloatField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('cancion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='series.cancionbiblioteca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
