# Generated by Django 6.0.7 on 2026-07-18 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0021_cancionbiblioteca_publicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='cancion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='comunidadpost',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='comunidadpost',
            name='audio_artista',
        ),
        migrations.RemoveField(
            model_name='comunidadpost',
            name='audio_titulo',
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=255)),
                ('contexto', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_personalizado', models.CharField(blank=True, max_length=255, null=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='series.encuesta')),
                ('serie_vinculada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='series.serie')),
                ('votos', models.ManyToManyField(blank=True, related_name='opciones_votadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CancionBiblioteca',
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
